spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
